Last login: Sun Dec 24 22:58:46 on ttys005
JOHNs-iMac:~ johnkenny$ /Users/johnkenny/.anaconda/navigator/a.tool ; exit;
(Server) bash-3.2$ cd /Users/johnkenny/Desktop/Premier\ League/Server\ APP/epl 
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

December 29, 2017 - 23:37:40
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[29/Dec/2017 23:38:08] "GET /requets HTTP/1.1" 301 0
[29/Dec/2017 23:38:08] "GET /requets/ HTTP/1.1" 200 75
Not Found: /favicon.ico
[29/Dec/2017 23:38:08] "GET /favicon.ico HTTP/1.1" 404 2068
^C(Server) bash-3.2$ python manage.py startapp footballdata
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

December 29, 2017 - 23:43:47
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[29/Dec/2017 23:44:01] "GET /footballdata/ HTTP/1.1" 200 40
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

December 29, 2017 - 23:54:05
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
^C(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

December 29, 2017 - 23:54:11
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
^C(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
(Server) bash-3.2$ python manage.py makemigrations footballdata
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Footballdata.Configdjango.contrib
(Server) bash-3.2$ python manage.py createsuperuser
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named Footballdata.Configdjango.contrib
(Server) bash-3.2$ python manage.py createsuperuser
Username (leave blank to use 'johnkenny'): jk
Email address: n00145905@student.iadt.ie
Password: 
Password (again): 
Superuser created successfully.
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).
December 30, 2017 - 23:52:04
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[30/Dec/2017 23:52:24] "GET /admin HTTP/1.1" 301 0
[30/Dec/2017 23:52:24] "GET /admin/ HTTP/1.1" 302 0
[30/Dec/2017 23:52:24] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1650
[30/Dec/2017 23:52:24] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[30/Dec/2017 23:52:24] "GET /static/admin/css/base.css HTTP/1.1" 200 16066
[30/Dec/2017 23:52:24] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[30/Dec/2017 23:52:24] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[30/Dec/2017 23:52:24] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[30/Dec/2017 23:52:31] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[30/Dec/2017 23:52:31] "GET /admin/ HTTP/1.1" 200 2776
[30/Dec/2017 23:52:31] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[30/Dec/2017 23:52:31] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[30/Dec/2017 23:52:31] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[30/Dec/2017 23:52:31] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[30/Dec/2017 23:52:34] "GET /admin/auth/user/ HTTP/1.1" 200 6462
[30/Dec/2017 23:52:34] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6591
[30/Dec/2017 23:52:34] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
[30/Dec/2017 23:52:34] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[30/Dec/2017 23:52:34] "GET /static/admin/js/core.js HTTP/1.1" 200 7976
[30/Dec/2017 23:52:34] "GET /static/admin/js/actions.js HTTP/1.1" 200 6501
[30/Dec/2017 23:52:34] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[30/Dec/2017 23:52:34] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
[30/Dec/2017 23:52:34] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
[30/Dec/2017 23:52:34] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8186
[30/Dec/2017 23:52:35] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[30/Dec/2017 23:52:35] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[30/Dec/2017 23:52:35] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[30/Dec/2017 23:52:35] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[30/Dec/2017 23:52:35] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[30/Dec/2017 23:56:36] "GET /admin/auth/user/1/change/ HTTP/1.1" 200 13481
[30/Dec/2017 23:56:36] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[30/Dec/2017 23:56:36] "GET /static/admin/css/forms.css HTTP/1.1" 200 8173
[30/Dec/2017 23:56:36] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7790
[30/Dec/2017 23:56:36] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 5755
[30/Dec/2017 23:56:36] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12389
[30/Dec/2017 23:56:36] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
[30/Dec/2017 23:56:36] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20529
[30/Dec/2017 23:56:36] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[30/Dec/2017 23:56:36] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
[30/Dec/2017 23:56:36] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[30/Dec/2017 23:56:36] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[30/Dec/2017 23:56:36] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[30/Dec/2017 23:56:36] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[30/Dec/2017 23:56:36] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
Performing system checks...

System check identified no issues (0 silenced).
December 30, 2017 - 23:59:35
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
^C(Server) bash-3.2$ python manage.py makemigrations footballdata
Migrations for 'footballdata':
  footballdata/migrations/0001_initial.py
    - Create model Player
    - Create model Team
    - Add field teams to player
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  Applying footballdata.0001_initial... OK
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:01:39
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[31/Dec/2017 00:01:40] "GET /admin/ HTTP/1.1" 200 2776
Unhandled exception in thread started by <function wrapper at 0x10d31fb18>
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 8, in <module>
    class Team(models.Model):
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 9, in Team
    code = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
NameError: name 'UUIDField' is not defined
^C(Server) bash-3.2$ python manage.py makemigrations footballdata
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 8, in <module>
    class Team(models.Model):
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 9, in Team
    code = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
NameError: name 'UUIDField' is not defined
(Server) bash-3.2$ python manage.py makemigrations footballdata
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 8, in <module>
    class Team(models.Model):
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 9, in Team
    code = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
NameError: name 'uuid' is not defined
(Server) bash-3.2$ python manage.py makemigrations footballdata
Migrations for 'footballdata':
  footballdata/migrations/0002_auto_20171231_0008.py
    - Remove field id from player
    - Remove field id from team
    - Alter field playerId on player
    - Alter field code on team
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  Applying footballdata.0002_auto_20171231_0008... OK
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:08:35
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:14:14
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:14:18
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:14:22
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
^C(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  No migrations to apply.
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:15:10
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[31/Dec/2017 00:15:13] "GET /admin/ HTTP/1.1" 200 3866
[31/Dec/2017 00:16:18] "GET /admin/footballdata/player/add/ HTTP/1.1" 200 14323
[31/Dec/2017 00:16:18] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:16:25] "GET /admin/ HTTP/1.1" 200 3866
[31/Dec/2017 00:28:48] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7602
[31/Dec/2017 00:28:48] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:29:05] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7775
[31/Dec/2017 00:29:05] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:29:10] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7773
[31/Dec/2017 00:29:10] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:29:16] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7771
[31/Dec/2017 00:29:16] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:29:23] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7771
[31/Dec/2017 00:29:23] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:29:56] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7780
[31/Dec/2017 00:29:56] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:30:38] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7786
[31/Dec/2017 00:30:38] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:30:43] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7785
[31/Dec/2017 00:30:43] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:30:44] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7785
[31/Dec/2017 00:30:44] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:31:02] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7797
[31/Dec/2017 00:31:02] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:31:28] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7765
[31/Dec/2017 00:31:28] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:31:32] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7771
[31/Dec/2017 00:31:32] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:32:15] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7786
[31/Dec/2017 00:32:15] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:32:22] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7796
[31/Dec/2017 00:32:22] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:33:26
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
^C(Server) bash-3.2$ python manage.py makemigrations footballdata
Migrations for 'footballdata':
  footballdata/migrations/0003_auto_20171231_0033.py
    - Alter field playerId on player
    - Alter field code on team
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  Applying footballdata.0003_auto_20171231_0033... OK
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:33:48
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[31/Dec/2017 00:33:52] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7748
[31/Dec/2017 00:33:52] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:34:02] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7748
[31/Dec/2017 00:34:02] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
Unhandled exception in thread started by <function wrapper at 0x1036b1c08>
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 10, in <module>
    class Team(models.Model):
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 11, in Team
    code                    = models.uuid(primary_key=True, default=uuid.uuid4)
AttributeError: 'module' object has no attribute 'uuid'
Unhandled exception in thread started by <function wrapper at 0x109375b90>
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 250, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 10, in <module>
    class Team(models.Model):
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 11, in Team
    code                    = models.uuid(primary_key=True)
AttributeError: 'module' object has no attribute 'uuid'
^C(Server) bash-3.2$ python manage.py makemigrations footballdata
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 10, in <module>
    class Team(models.Model):
  File "/Users/johnkenny/Desktop/Premier League/Server APP/epl/footballdata/models.py", line 11, in Team
    code                    = models.uuid(primary_key=True)
AttributeError: 'module' object has no attribute 'uuid'
(Server) bash-3.2$ python manage.py makemigrations footballdata
You are trying to add a non-nullable field 'id' to player without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> 
Please enter some code, or 'exit' (with no quotes) to exit.
>>> exit
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
(Server) bash-3.2$ python manage.py makemigrations footballdata
You are trying to add a non-nullable field 'id' to player without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: ^CTraceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 177, in handle
    migration_name=self.migration_name,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 47, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 188, in _detect_changes
    self.generate_added_fields()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 827, in generate_added_fields
    self._generate_added_field(app_label, model_name, field_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 847, in _generate_added_field
    field.default = self.questioner.ask_not_null_addition(field_name, model_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/questioner.py", line 159, in ask_not_null_addition
    "Quit, and let me add a default in models.py",
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/questioner.py", line 99, in _choice_input
    result = input("Select an option: ")
KeyboardInterrupt
(Server) bash-3.2$ python manage.py makemigrations footballdata
You are trying to add a non-nullable field 'id' to player without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: ^CTraceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 177, in handle
    migration_name=self.migration_name,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 47, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 188, in _detect_changes
    self.generate_added_fields()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 827, in generate_added_fields
    self._generate_added_field(app_label, model_name, field_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/autodetector.py", line 847, in _generate_added_field
    field.default = self.questioner.ask_not_null_addition(field_name, model_name)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/questioner.py", line 159, in ask_not_null_addition
    "Quit, and let me add a default in models.py",
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/questioner.py", line 99, in _choice_input
    result = input("Select an option: ")
KeyboardInterrupt
(Server) bash-3.2$ 
(Server) bash-3.2$ python manage.py makemigrations footballdata
No changes detected in app 'footballdata'
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  No migrations to apply.
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:41:31
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[31/Dec/2017 00:41:34] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7748
[31/Dec/2017 00:41:34] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:41:36] "GET /admin/footballdata/ HTTP/1.1" 200 2679
Internal Server Error: /admin/footballdata/team/
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 79, in __init__
    self.get_results(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 177, in get_results
    result_count = paginator.count
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/query.py", line 363, in count
    return self.query.get_count(using=self.db)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 498, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 479, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: footballdata_team
[31/Dec/2017 00:41:41] "GET /admin/footballdata/team/ HTTP/1.1" 500 153790
[31/Dec/2017 00:41:46] "GET /admin/footballdata/ HTTP/1.1" 200 2679
[31/Dec/2017 00:41:48] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7748
[31/Dec/2017 00:41:48] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:42:00] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7855
[31/Dec/2017 00:42:00] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:42:05] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7845
[31/Dec/2017 00:42:05] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:42:08] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7845
[31/Dec/2017 00:42:09] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:42:10] "GET /admin/footballdata/ HTTP/1.1" 200 2679
Internal Server Error: /admin/footballdata/team/
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 79, in __init__
    self.get_results(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 177, in get_results
    result_count = paginator.count
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/query.py", line 363, in count
    return self.query.get_count(using=self.db)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 498, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 479, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: footballdata_team
[31/Dec/2017 00:42:12] "GET /admin/footballdata/team/ HTTP/1.1" 500 153789
[31/Dec/2017 00:42:28] "GET /admin/footballdata/ HTTP/1.1" 200 2679
Performing system checks...

System check identified no issues (0 silenced).
December 31, 2017 - 00:43:09
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
^C(Server) bash-3.2$ python manage.py makemigrations footballdata
Migrations for 'footballdata':
  footballdata/migrations/0004_auto_20171231_0043.py
    - Alter field playerId on player
    - Alter field code on team
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  Applying footballdata.0004_auto_20171231_0043...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 215, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 513, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 262, in _alter_field
    self._remake_table(model, alter_field=(old_field, new_field))
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 193, in _remake_table
    self.alter_db_table(model, temp_model._meta.db_table, model._meta.db_table)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 391, in alter_db_table
    "new_table": self.quote_name(new_db_table),
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 119, in execute
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: footballdata_player
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): footballdata.
Run 'python manage.py migrate' to apply them.

December 31, 2017 - 00:44:46
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[31/Dec/2017 00:44:57] "GET /admin/footballdata/ HTTP/1.1" 200 2679
[31/Dec/2017 00:44:59] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7626
[31/Dec/2017 00:44:59] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
Internal Server Error: /admin/footballdata/team/add/
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1440, in _changeform_view
    if form.is_valid():
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/forms.py", line 386, in full_clean
    self._post_clean()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/models.py", line 402, in _post_clean
    self.validate_unique()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/models.py", line 411, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/base.py", line 1032, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/base.py", line 1129, in _perform_unique_checks
    if qs.exists():
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/query.py", line 667, in exists
    return self.query.has_results(using=self.db)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 516, in has_results
    return compiler.has_results()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 845, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: footballdata_team
[31/Dec/2017 00:45:13] "POST /admin/footballdata/team/add/ HTTP/1.1" 500 175659
Not Found: /admin/footballdat
[31/Dec/2017 00:45:21] "GET /admin/footballdat HTTP/1.1" 404 4322
[31/Dec/2017 00:45:27] "GET /admin/footballdata HTTP/1.1" 301 0
[31/Dec/2017 00:45:27] "GET /admin/footballdata/ HTTP/1.1" 200 2679
Internal Server Error: /admin/footballdata/team/
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 79, in __init__
    self.get_results(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 177, in get_results
    result_count = paginator.count
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/query.py", line 363, in count
    return self.query.get_count(using=self.db)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 498, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 479, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: footballdata_team
[31/Dec/2017 00:45:29] "GET /admin/footballdata/team/ HTTP/1.1" 500 153784
[31/Dec/2017 00:45:32] "GET /admin/footballdata/ HTTP/1.1" 200 2679
[31/Dec/2017 00:45:33] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7626
[31/Dec/2017 00:45:33] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:45:36] "GET /admin/footballdata/ HTTP/1.1" 200 2679
Internal Server Error: /admin/footballdata/team/
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 79, in __init__
    self.get_results(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 177, in get_results
    result_count = paginator.count
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/paginator.py", line 79, in count
    return self.object_list.count()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/query.py", line 363, in count
    return self.query.get_count(using=self.db)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 498, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 479, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: footballdata_team
[31/Dec/2017 00:45:37] "GET /admin/footballdata/team/ HTTP/1.1" 500 153790
[31/Dec/2017 00:45:40] "GET /admin/footballdata/ HTTP/1.1" 200 2679
[31/Dec/2017 00:45:41] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7626
[31/Dec/2017 00:45:41] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
Internal Server Error: /admin/footballdata/team/add/
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1440, in _changeform_view
    if form.is_valid():
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/forms.py", line 183, in is_valid
    return self.is_bound and not self.errors
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/forms.py", line 386, in full_clean
    self._post_clean()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/models.py", line 402, in _post_clean
    self.validate_unique()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/forms/models.py", line 411, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/base.py", line 1032, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/base.py", line 1129, in _perform_unique_checks
    if qs.exists():
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/query.py", line 667, in exists
    return self.query.has_results(using=self.db)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/query.py", line 516, in has_results
    return compiler.has_results()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 845, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: footballdata_team
[31/Dec/2017 00:45:55] "POST /admin/footballdata/team/add/ HTTP/1.1" 500 175700
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x1099ad2a8>
Traceback (most recent call last):
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 405, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
footballdata.Player.playerId: (fields.E130) DecimalFields must define a 'decimal_places' attribute.
footballdata.Player.playerId: (fields.E132) DecimalFields must define a 'max_digits' attribute.
footballdata.Team.code: (fields.E130) DecimalFields must define a 'decimal_places' attribute.
footballdata.Team.code: (fields.E132) DecimalFields must define a 'max_digits' attribute.

System check identified 4 issues (0 silenced).
Performing system checks...

System check identified no issues (0 silenced).

You have 1 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): footballdata.
Run 'python manage.py migrate' to apply them.

December 31, 2017 - 00:49:44
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
^C(Server) bash-3.2$ python manage.py makemigrations footballdata
Migrations for 'footballdata':
  footballdata/migrations/0005_auto_20171231_0049.py
    - Alter field playerId on player
    - Alter field code on team
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  Applying footballdata.0004_auto_20171231_0043...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 215, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 513, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 262, in _alter_field
    self._remake_table(model, alter_field=(old_field, new_field))
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 193, in _remake_table
    self.alter_db_table(model, temp_model._meta.db_table, model._meta.db_table)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 391, in alter_db_table
    "new_table": self.quote_name(new_db_table),
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 119, in execute
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: footballdata_player
(Server) bash-3.2$ python manage.py makemigrations footballdata
Migrations for 'footballdata':
  footballdata/migrations/0006_auto_20171231_0051.py
    - Alter field playerId on player
    - Alter field code on team
(Server) bash-3.2$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, footballdata, sessions
Running migrations:
  Applying footballdata.0004_auto_20171231_0043...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 215, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 513, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 262, in _alter_field
    self._remake_table(model, alter_field=(old_field, new_field))
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 193, in _remake_table
    self.alter_db_table(model, temp_model._meta.db_table, model._meta.db_table)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 391, in alter_db_table
    "new_table": self.quote_name(new_db_table),
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 119, in execute
    cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/johnkenny/anaconda3/envs/Server/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: footballdata_player
(Server) bash-3.2$ python manage.py runserver 8080
Performing system checks...

System check identified no issues (0 silenced).

You have 3 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): footballdata.
Run 'python manage.py migrate' to apply them.

December 31, 2017 - 00:51:59
Django version 1.11, using settings 'epl.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
[31/Dec/2017 00:52:21] "GET /admin/footballdata/team/add/ HTTP/1.1" 200 7748
[31/Dec/2017 00:52:21] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:53:08] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7849
[31/Dec/2017 00:53:08] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:53:13] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7845
[31/Dec/2017 00:53:13] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:53:19] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7869
[31/Dec/2017 00:53:19] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:53:20] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7869
[31/Dec/2017 00:53:20] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
[31/Dec/2017 00:53:21] "POST /admin/footballdata/team/add/ HTTP/1.1" 200 7869
[31/Dec/2017 00:53:21] "GET /admin/jsi18n/ HTTP/1.1" 200 5798
^C(Server) bash-3.2$ 
